-- MySQL Script generated by MySQL Workbench
-- Пт 02 июн 2017 18:29:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hosting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hosting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hosting` DEFAULT CHARACTER SET utf8 ;
USE `hosting` ;

-- -----------------------------------------------------
-- Table `hosting`.`name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phonenumber` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosting`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(60) NULL,
  `password` VARCHAR(32) NULL,
  `email` VARCHAR(255) NULL,
  `directory` VARCHAR(255) NULL DEFAULT '/',
  `name_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_name_idx` (`name_id` ASC),
  CONSTRAINT `fk_users_name`
    FOREIGN KEY (`name_id`)
    REFERENCES `hosting`.`name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosting`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(32) NULL,
  `directory` VARCHAR(255) NULL DEFAULT '/',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosting`.`departaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`departaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
