-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 13:58:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Students
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Students` ;

-- -----------------------------------------------------
-- Schema Students
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Students` DEFAULT CHARACTER SET utf8 ;
USE `Students` ;

-- -----------------------------------------------------
-- Table `Students`.`Специальности`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Students`.`Специальности` ;

CREATE TABLE IF NOT EXISTS `Students`.`Специальности` (
  `код` INT NOT NULL,
  `наименование` VARCHAR(255) NOT NULL,
  `уровень` VARCHAR(5) NOT NULL,
  `описание` TINYTEXT NULL,
  PRIMARY KEY (`код`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Students`.`Группы`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Students`.`Группы` ;

CREATE TABLE IF NOT EXISTS `Students`.`Группы` (
  `шифр` VARCHAR(15) NOT NULL,
  `курс` INT(1) NOT NULL,
  `год_поступления` YEAR NOT NULL,
  `код_специальности` INT NOT NULL,
  PRIMARY KEY (`шифр`),
  INDEX `fk_Группы_Специальности_idx` (`код_специальности` ASC),
  CONSTRAINT `fk_Группы_Специальности`
    FOREIGN KEY (`код_специальности`)
    REFERENCES `Students`.`Специальности` (`код`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Students`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Students`.`Студенты` ;

CREATE TABLE IF NOT EXISTS `Students`.`Студенты` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `фамилия` VARCHAR(60) NOT NULL,
  `имя` VARCHAR(60) NOT NULL,
  `отчество` VARCHAR(60) NULL,
  `шифр_группы` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_Students_Группы1_idx` (`шифр_группы` ASC),
  CONSTRAINT `fk_Students_Группы1`
    FOREIGN KEY (`шифр_группы`)
    REFERENCES `Students`.`Группы` (`шифр`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Students`.`Личные_карточки`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Students`.`Личные_карточки` ;

CREATE TABLE IF NOT EXISTS `Students`.`Личные_карточки` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `дата_рождения` DATETIME NULL,
  `телефон` VARCHAR(30) NULL,
  `адрес` VARCHAR(255) NULL,
  `примечание` TINYTEXT NULL,
  `номер_студента` INT NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_Личные_карточки_Students1_idx` (`номер_студента` ASC),
  CONSTRAINT `fk_Личные_карточки_Students1`
    FOREIGN KEY (`номер_студента`)
    REFERENCES `Students`.`Студенты` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
